Rails 6.1 support
rails-sqlserver/activerecord-sqlserver-adapter pull request #853
Opened 2021-02-05 10:55 UTC by lk0001

Adds Rails 6.1 support.
Changes:
- use `ActiveRecord::ConnectionAdapters::SchemaCreation` instead of `ActiveRecord::ConnectionAdapters::AbstractAdapter::SchemaCreation`
- accept 2 arguments in `SQLServerRealTransaction#initialize` instead of 3

I don't know if that's all, but basic testing didn't reveal other issues.

2021-04-07 18:01 UTC, wpolicarpo requested changes

2021-04-07 18:02 UTC, wpolicarpo commented
Can you also rebase your branch to get the latest CI changes made to `main` branch?

2021-04-13 19:24 UTC, merged

2021-04-13 19:50 UTC, fxgallego commented
Hi @wpolicarpo and @lk0001, I was using this branch in development and I have an error with some code that worked before the version for rails 5, fir example:
```
# Here self is a Class
user.model_permissions.where(permitted_model_type: self)
```
In older versions, passing a class as argument was casted to String.
Now it raises `can't cast Class`
I'm going to change my code to use `self.name` but maybe this is something that is not working correctly and it has no tests.
As I migrated from 4.2 to 6.1 I didn't notice this until now.

2021-04-13 20:11 UTC, wpolicarpo commented
Hi @fxgallego. Rails 6.1 is still WIP and I don't recommend you to use this branch (or `main` now that this one got merged) yet, unless are willing to dig into the issues you may find.

2021-04-13 20:16 UTC, fxgallego commented
Sorry I mean the branch from @joshleblanc. I've been using it in development from some time and I only found this problem. I'm not using it in production